# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
  pull_request:
    branches:
      - main
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # automatically cancel the workflow if it runs longer than 10 minutes
    timeout-minutes: 10
    # The docker image to use for the container
    container:
      image: ghcr.io/tudalgo/algotex:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v4

      # 2. Build the document
      - name: "Build the document"
        run: |
          make -j
          mv build/*.pdf .

      # 3. Upload artifacts to GitHub
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Workshop Folien
          path: "*.pdf"
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      # 4. Get Date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S.%N')"

      # 5. create a release
      - name: Create a release
        if: ${{ !env.ACT && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: snapshot-${{ steps.date.outputs.date }}
          name: snapshot-release-${{ steps.date.outputs.date }}
          files: "*.pdf"
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
